language: java
jdk:
- openjdk8
before_install:
- nvm install --lts
install:
- npm install
script:
- npx gulp buildAll
- chmod +x gradlew
- ./gradlew test bootJar

env:
  - secure: yHmxYCzgUl8jQKzUdinIcyUqvHmQCBmx4ZusD790l/zvyJv1qw7SNESyw7o/K+G9XuuumdNqtO6h+LK96QbdGDHZNhRUaIpoOaKyQpQgeeIst4zQbp2KsQ4eNZzBE6MfkOUifUu/T1irnFj7v7PZUufD39+QLNOsfFwZo/r2sONUTlevg7wNgGTcpqdm09W+XjNPn/ITWmT/uIwyjbgCXIp8Okk8ngB49eRMuknqn27R63Si5VmshPRLHFCwjaWQPxu/bCHg+0VkqLxYtL8m0aiY0kz921C/q/PN/KB3TkaCyqYCl6PQsgwZtC6yoPK+6eFnsPx67i1uN9N1+L6IatofAXdzcBM8RMCNtCLAAA0VcudD3DwZJUZAhwQc22eFVktqMotyViLQSGQaU3AZj6O4lZacvi9d0V4P0OoBw7lJiCvYJyRkHTpKbT6yUSD5nK39KtFNC532csMATKgVyaFk91rvPK3VKsqkqu22aS2M9KIW4Z5nimTq9ke/yHyZmZQP5ffLtb6Di+z6CfpkaQaZ+dgeA3IoOK4mb+Dcl/xC7zEoaOtTuGvum3UZK3TO2SplDcBkF1Sx4LuTElmAv3TLJvnN4DRfhLcrqI6iXnfKjtjDrLy0uiqlB5/9Ahp7LcGHv6R4q2NiQZlgTqWGYT+tXylaTminJ8fh6BwmXqw=

before_deploy:
  - chmod +x ci/blue-green-deploy.sh
  - chmod +x ci/smoke-test.sh

deploy:
  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: tech+ci@fivium.co.uk
    password:
      secure: lTcJ/vx91bvLQwUpm3vAcUkOskmYs79tPICI7aupjCy+Gd0+9Ssv8loSbtyFgx40DCnLPGBICO+WEns/0zqNJvtO4ujUIiyqB/sTzw1dqTFVbpg82xRCzYqK33iaeX5DgF6GrcSWSzw4ZbAiTW7ssmAXtD0MczzMncb7KojPuNF0JNAmTfwrycY1SdNWJW4n7Z2o9+CP4iWUSPXBs2ds/Bf38drIkwgKgUxZf4UyR7SjgermPTqVZ3Pyo4oBdrINH6yUfZEsPxVrkfEBIVKFCzOOuvmoWm6ccgdtjdQJSSgkxFxnmTVhm80ILEKrOi2cn+x8d33FttjYyivIbYrYXlKXe2rOQaadi53W3zhNmYLgEpz/3YY9gPemmeNC7ni9fYnJ6p9jrSPKEqnLohrKSxbmUnpJR0ujYes0uWgsB5VVgYxTMPONtVykJAM2GkSFpkAD2RdQvcVRR77N6WvCqIg1FL3wthtxFY0/vAB1fnuQjwUAFI9PNP5jLzJo6uYvYY4ULhWaXg2pQlQiwWPBP41IgrGmVbV79PTCldCuwzN7uuhdiJH0lswLVertumv8OgUv+YtrwEvzDZEaz6wDtvbqshT7E01oQsnUMVeSYILevvRwG3EduVnmUA4Z6kjyWB4gx0aqQpd8mD0BRtz6D2lIx1i4fJY1HujiHkTRsVw=
    organization: beis-energy-label-service
    space: energy-label-service-dev
    manifest: manifest-dev.yml
    on:
      repo: UKGovernmentBEIS/energy-label-service
      branch: develop

  - provider: cloudfoundry
    api: https://api.london.cloud.service.gov.uk
    username: tech+ci@fivium.co.uk
    password:
      secure: lTcJ/vx91bvLQwUpm3vAcUkOskmYs79tPICI7aupjCy+Gd0+9Ssv8loSbtyFgx40DCnLPGBICO+WEns/0zqNJvtO4ujUIiyqB/sTzw1dqTFVbpg82xRCzYqK33iaeX5DgF6GrcSWSzw4ZbAiTW7ssmAXtD0MczzMncb7KojPuNF0JNAmTfwrycY1SdNWJW4n7Z2o9+CP4iWUSPXBs2ds/Bf38drIkwgKgUxZf4UyR7SjgermPTqVZ3Pyo4oBdrINH6yUfZEsPxVrkfEBIVKFCzOOuvmoWm6ccgdtjdQJSSgkxFxnmTVhm80ILEKrOi2cn+x8d33FttjYyivIbYrYXlKXe2rOQaadi53W3zhNmYLgEpz/3YY9gPemmeNC7ni9fYnJ6p9jrSPKEqnLohrKSxbmUnpJR0ujYes0uWgsB5VVgYxTMPONtVykJAM2GkSFpkAD2RdQvcVRR77N6WvCqIg1FL3wthtxFY0/vAB1fnuQjwUAFI9PNP5jLzJo6uYvYY4ULhWaXg2pQlQiwWPBP41IgrGmVbV79PTCldCuwzN7uuhdiJH0lswLVertumv8OgUv+YtrwEvzDZEaz6wDtvbqshT7E01oQsnUMVeSYILevvRwG3EduVnmUA4Z6kjyWB4gx0aqQpd8mD0BRtz6D2lIx1i4fJY1HujiHkTRsVw=
    organization: beis-energy-label-service
    space: energy-label-service-qa
    manifest: manifest-qa.yml
    on:
      repo: UKGovernmentBEIS/energy-label-service
      branch: qa

  - provider: script
    skip_cleanup: true
    script: ci/blue-green-deploy.sh \
      api=api.london.cloud.service.gov.uk \
      app=energy-label-service-prod \
      org=beis-energy-label-service \
      space=energy-label-service-prod \
      user=tech+ci@fivium.co.uk \
      manifest=manifest-prod.yml \
      test=ci/smoke-test.sh \
      delete=false
    on:
      repo: UKGovernmentBEIS/energy-label-service
      branch: master